kind: Service
apiVersion: v1
metadata:
  name: kdb-wac-webapi
spec:
  selector:
    pod: kdb-wac-webapi-label
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: webapi-port