/*
 * Hospital Management API
 *
 * API for managing hospital ambulances, procedures, and payments.
 *
 * API version: 1.0.0
 * Contact: xkokavecs@stuba.sk
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package ambulance

import (
	"github.com/gin-gonic/gin"
)

type PaymentManagementAPI interface {


    // CreatePayment Post /api/payments
    // Create a new payment record 
     CreatePayment(c *gin.Context)

    // DeletePayment Delete /api/payments/:paymentId
    // Delete a payment record 
     DeletePayment(c *gin.Context)

    // GetPaymentById Get /api/payments/:paymentId
    // Get payment record details 
     GetPaymentById(c *gin.Context)

    // GetPayments Get /api/payments
    // Get list of payment records 
     GetPayments(c *gin.Context)

    // UpdatePayment Put /api/payments/:paymentId
    // Update payment record details 
     UpdatePayment(c *gin.Context)

}