/*
 * Hospital Management API
 *
 * API for managing hospital ambulances, procedures, and payments.
 *
 * API version: 1.0.0
 * Contact: xkokavecs@stuba.sk
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package ambulance

import (
	"github.com/gin-gonic/gin"
)

type ProcedureManagementAPI interface {


    // CreateProcedure Post /api/procedures
    // Create a new procedure 
     CreateProcedure(c *gin.Context)

    // DeleteProcedure Delete /api/procedures/:procedureId
    // Delete a procedure 
     DeleteProcedure(c *gin.Context)

    // GetProcedureById Get /api/procedures/:procedureId
    // Get procedure details 
     GetProcedureById(c *gin.Context)

    // GetProcedures Get /api/procedures
    // Get list of procedures 
     GetProcedures(c *gin.Context)

    // UpdateProcedure Put /api/procedures/:procedureId
    // Update procedure details 
     UpdateProcedure(c *gin.Context)

}