/*
 * Hospital Management API
 *
 * API for managing hospital ambulances, procedures, and payments.
 *
 * API version: 1.0.0
 * Contact: xkokavecs@stuba.sk
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package ambulance

type Ambulance struct {

    // Unique identifier of the ambulance.
    Id string `json:"id"`

    // Name of the ambulance.
    Name string `json:"name"`

    // Location or base of the ambulance.
    Location string `json:"location"`

    // Department the ambulance belongs to.
    Department string `json:"department"`

    // Capacity of the ambulance (number of patients it can serve).
    Capacity int `json:"capacity"`

    // Current status of the ambulance (e.g., Available, Occupied).
    Status string `json:"status"`
}
