/*
 * Hospital Management API
 *
 * API for managing hospital ambulances, procedures, and payments.
 *
 * API version: 1.0.0
 * Contact: xkokavecs@stuba.sk
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package ambulance

type Ambulance struct {

	// Unique identifier of the ambulance.
	Id string `json:"id"`

	// Name of the ambulance.
	Name string `json:"name"`

	// Location or base of the ambulance.
	Location string `json:"location"`

	// Name of the driver in charge.
	DriverName string `json:"driverName"`
}
