/*
 * Hospital Management API
 *
 * API for managing hospital ambulances, procedures, and payments.
 *
 * API version: 1.0.0
 * Contact: xkokavecs@stuba.sk
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package ambulance

type Procedure struct {

	// Unique identifier of the procedure.
	Id string `json:"id"`

	// Name or identifier of the patient.
	Patient string `json:"patient"`

	// Type of visit.
	VisitType string `json:"visitType"`

	// Price of the procedure.
	Price float32 `json:"price"`

	// Payer for the procedure.
	Payer string `json:"payer"`

	// Identifier of the ambulance associated with the procedure.
	AmbulanceId string `json:"ambulanceId"`
}
