/*
 * Hospital Management API
 *
 * API for managing hospital ambulances, procedures, and payments.
 *
 * API version: 1.0.0
 * Contact: xkokavecs@stuba.sk
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package ambulance

type Payment struct {

	// Unique identifier of the payment record.
	Id string `json:"id"`

	// Identifier of the related procedure.
	ProcedureId string `json:"procedureId"`

	// Insurance or payer for the procedure.
	Insurance string `json:"insurance"`

	// Payment amount.
	Amount float32 `json:"amount"`
}
