/*
 * Hospital Management API
 *
 * API for managing hospital ambulances, procedures, and payments.
 *
 * API version: 1.0.0
 * Contact: xkokavecs@stuba.sk
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package ambulance

import (
	"time"
)

type Payment struct {

	// Unique identifier of the payment record.
	Id string `json:"id"`

	// Name of the payment or transaction.
	Name string `json:"name,omitempty"`

	// Description of the payment.
	Description string `json:"description,omitempty"`

	// Identifier of the related procedure.
	ProcedureId string `json:"procedure_id"`

	// Insurance or payer for the procedure.
	Insurance string `json:"insurance"`

	// Payment amount.
	Amount float32 `json:"amount"`

	// Date and time when the payment was made (ISO 8601).
	Timestamp time.Time `json:"timestamp,omitempty"`
}
