/*
 * Hospital Management API
 *
 * API for managing hospital ambulances, procedures, and payments.
 *
 * API version: 1.0.0
 * Contact: xkokavecs@stuba.sk
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package ambulance

type Procedure struct {

    // Unique identifier of the procedure.
    Id string `json:"id"`

    // Name of the procedure.
    Name string `json:"name"`

    // Description of the procedure.
    Description string `json:"description"`

    // Name or identifier of the patient.
    Patient string `json:"patient"`

    // Type of visit (e.g., emergency, checkup, follow-up).
    VisitType string `json:"visit_type"`

    // Price of the procedure.
    Price float64 `json:"price"`

    // Payer for the procedure.
    Payer string `json:"payer"`

    // Identifier of the ambulance associated with the procedure.
    AmbulanceId string `json:"ambulance_id"`

    // Date and time of the procedure in ISO 8601 format.
    Timestamp string `json:"timestamp,omitempty"`
}
