/*
 * Hospital Management API
 *
 * API for managing hospital ambulances, procedures, and payments.
 *
 * API version: 1.0.0
 * Contact: xkokavecs@stuba.sk
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

 package ambulance

 import (
	 "net/http"
 
	 "github.com/gin-gonic/gin"
 )
 
 // Route is the information for every URI.
 type Route struct {
	 Name        string
	 Method      string
	 Pattern     string
	 HandlerFunc gin.HandlerFunc
 }
 
 // NewRouter returns a new router.
 func NewRouter(handleFunctions ApiHandleFunctions) *gin.Engine {
	 return NewRouterWithGinEngine(gin.Default(), handleFunctions)
 }
 
 // NewRouterWithGinEngine adds routes to an existing gin engine.
 func NewRouterWithGinEngine(router *gin.Engine, handleFunctions ApiHandleFunctions) *gin.Engine {
	 for _, route := range getRoutes(handleFunctions) {
		 if route.HandlerFunc == nil {
			 route.HandlerFunc = DefaultHandleFunc
		 }
		 switch route.Method {
		 case http.MethodGet:
			 router.GET(route.Pattern, route.HandlerFunc)
		 case http.MethodPost:
			 router.POST(route.Pattern, route.HandlerFunc)
		 case http.MethodPut:
			 router.PUT(route.Pattern, route.HandlerFunc)
		 case http.MethodPatch:
			 router.PATCH(route.Pattern, route.HandlerFunc)
		 case http.MethodDelete:
			 router.DELETE(route.Pattern, route.HandlerFunc)
		 }
	 }
	 return router
 }
 
 // DefaultHandleFunc handles routes that are not implemented.
 func DefaultHandleFunc(c *gin.Context) {
	 c.String(http.StatusNotImplemented, "501 not implemented")
 }
 
 // ApiHandleFunctions aggregates the API interface implementations.
 type ApiHandleFunctions struct {
	 AmbulanceManagementAPI   AmbulanceManagementAPI
	 PaymentManagementAPI     PaymentManagementAPI
	 ProcedureManagementAPI   ProcedureManagementAPI
 }
 
 // getRoutes defines the full route list and their handler bindings.
 func getRoutes(handleFunctions ApiHandleFunctions) []Route {
	 return []Route{
		 // Ambulance routes
		 {"CreateAmbulance", http.MethodPost, "/api/ambulances", handleFunctions.AmbulanceManagementAPI.CreateAmbulance},
		 {"DeleteAmbulance", http.MethodDelete, "/api/ambulances/:ambulanceId", handleFunctions.AmbulanceManagementAPI.DeleteAmbulance},
		 {"GetAmbulanceById", http.MethodGet, "/api/ambulances/:ambulanceId", handleFunctions.AmbulanceManagementAPI.GetAmbulanceById},
		 {"GetAmbulanceSummary", http.MethodGet, "/api/ambulances/:ambulanceId/summary", handleFunctions.AmbulanceManagementAPI.GetAmbulanceSummary},
		 {"GetAmbulances", http.MethodGet, "/api/ambulances", handleFunctions.AmbulanceManagementAPI.GetAmbulances},
		 {"UpdateAmbulance", http.MethodPut, "/api/ambulances/:ambulanceId", handleFunctions.AmbulanceManagementAPI.UpdateAmbulance},
		{"GetProceduresByAmbulance", http.MethodGet, "/api/ambulances/:ambulanceId/procedures", handleFunctions.AmbulanceManagementAPI.GetProceduresByAmbulance},
		
		 // Payment routes
		 {"CreatePayment", http.MethodPost, "/api/payments", handleFunctions.PaymentManagementAPI.CreatePayment},
		 {"DeletePayment", http.MethodDelete, "/api/payments/:paymentId", handleFunctions.PaymentManagementAPI.DeletePayment},
		 {"GetPaymentById", http.MethodGet, "/api/payments/:paymentId", handleFunctions.PaymentManagementAPI.GetPaymentById},
		 {"GetPayments", http.MethodGet, "/api/payments", handleFunctions.PaymentManagementAPI.GetPayments},
		 {"UpdatePayment", http.MethodPut, "/api/payments/:paymentId", handleFunctions.PaymentManagementAPI.UpdatePayment},
 
		 // Procedure routes
		 {"CreateProcedure", http.MethodPost, "/api/procedures", handleFunctions.ProcedureManagementAPI.CreateProcedure},
		 {"DeleteProcedure", http.MethodDelete, "/api/procedures/:procedureId", handleFunctions.ProcedureManagementAPI.DeleteProcedure},
		 {"GetProcedureById", http.MethodGet, "/api/procedures/:procedureId", handleFunctions.ProcedureManagementAPI.GetProcedureById},
		 {"GetProcedures", http.MethodGet, "/api/procedures", handleFunctions.ProcedureManagementAPI.GetProcedures},
		 {"UpdateProcedure", http.MethodPut, "/api/procedures/:procedureId", handleFunctions.ProcedureManagementAPI.UpdateProcedure},
	 }
 }
 